from custom_token import TokenEnum

reserved_words = {
  # class stereotypes
  "event": ("EVENT", TokenEnum.CLASS_STEREOTYPES),
  "situation": ("SITUATION", TokenEnum.CLASS_STEREOTYPES),
  "process": ("PROCESS", TokenEnum.CLASS_STEREOTYPES),
  "category": ("CATEGORY", TokenEnum.CLASS_STEREOTYPES),
  "mixin": ("MIXIN", TokenEnum.CLASS_STEREOTYPES),
  "phaseMixin": ("PHASEMIXIN", TokenEnum.CLASS_STEREOTYPES),
  "roleMixin": ("ROLEMIXIN", TokenEnum.CLASS_STEREOTYPES),
  "historicalRoleMixin": ("HISTORICALROLEMIXIN", TokenEnum.CLASS_STEREOTYPES),
  "kind": ("KIND", TokenEnum.CLASS_STEREOTYPES),
  "collective": ("COLLECTIVE", TokenEnum.CLASS_STEREOTYPES),
  "quantity": ("QUANTITY", TokenEnum.CLASS_STEREOTYPES),
  "quality": ("QUALITY", TokenEnum.CLASS_STEREOTYPES),
  "mode": ("MODE", TokenEnum.CLASS_STEREOTYPES),
  "intrisicMode": ("INTRISICMODE", TokenEnum.CLASS_STEREOTYPES),
  "extrinsicMode": ("EXTRINSICMODE", TokenEnum.CLASS_STEREOTYPES),
  "subkind": ("SUBKIND", TokenEnum.CLASS_STEREOTYPES),
  "phase": ("PHASE", TokenEnum.CLASS_STEREOTYPES),
  "role": ("ROLE", TokenEnum.CLASS_STEREOTYPES),
  "historicalRole": ("HISTORICALROLE", TokenEnum.CLASS_STEREOTYPES),
  # relation stereotypes
  "material": ("MATERIAL", TokenEnum.RELATION_STEREOTYPES),
  "derivation": ("DERIVATION", TokenEnum.RELATION_STEREOTYPES),
  "comparative": ("COMPARATIVE", TokenEnum.RELATION_STEREOTYPES),
  "mediation": ("MEDIATION", TokenEnum.RELATION_STEREOTYPES),
  "characterization": ("CHARACTERIZATION", TokenEnum.RELATION_STEREOTYPES),
  "externalDependence": ("EXTERNALDEPENDENCE", TokenEnum.RELATION_STEREOTYPES),
  "componentOf": ("COMPONENTOF", TokenEnum.RELATION_STEREOTYPES),
  "memberOf": ("MEMBEROF", TokenEnum.RELATION_STEREOTYPES),
  "subCollectionOf": ("SUBCOLLECTIONOF", TokenEnum.RELATION_STEREOTYPES),
  "subQualityOf": ("SUBQUALITYOF", TokenEnum.RELATION_STEREOTYPES),
  "instantiation": ("INSTANTIATION", TokenEnum.RELATION_STEREOTYPES),
  "termination": ("TERMINATION", TokenEnum.RELATION_STEREOTYPES),
  "participational": ("PARTICIPATIONAL", TokenEnum.RELATION_STEREOTYPES),
  "participation": ("PARTICIPATION", TokenEnum.RELATION_STEREOTYPES),
  "historicalDependence": ("HISTORICALDEPENDENCE", TokenEnum.RELATION_STEREOTYPES),
  "creation": ("CREATION", TokenEnum.RELATION_STEREOTYPES),
  "manifestation": ("MANIFESTATION", TokenEnum.RELATION_STEREOTYPES),
  "bringsAbout": ("BRINGSABOUT", TokenEnum.RELATION_STEREOTYPES),
  "triggers": ("TRIGGERS", TokenEnum.RELATION_STEREOTYPES),
  "composition": ("COMPOSITION", TokenEnum.RELATION_STEREOTYPES),
  "aggregation": ("AGGREGATION", TokenEnum.RELATION_STEREOTYPES),
  "inherence": ("INHERENCE", TokenEnum.RELATION_STEREOTYPES),
  "value": ("VALUE", TokenEnum.RELATION_STEREOTYPES),
  "formal": ("FORMAL", TokenEnum.RELATION_STEREOTYPES),
  "constitution": ("CONSTITUTION", TokenEnum.RELATION_STEREOTYPES),
  # native types
  "number": ("NUMBER", TokenEnum.NATIVE_TYPES),
  "string": ("STRING", TokenEnum.NATIVE_TYPES),
  "boolean": ("BOOLEAN", TokenEnum.NATIVE_TYPES),
  "date": ("DATE", TokenEnum.NATIVE_TYPES),
  "time": ("TIME", TokenEnum.NATIVE_TYPES),
  "datetime": ("DATETIME", TokenEnum.NATIVE_TYPES),
  # meta-attributes
  "ordered": ("ORDERED", TokenEnum.META_ATTRIBUTES),
  "const": ("CONST", TokenEnum.META_ATTRIBUTES),
  "derived": ("DERIVED", TokenEnum.META_ATTRIBUTES),
  "subsets": ("SUBSETS", TokenEnum.META_ATTRIBUTES),
  "redefines": ("REDEFINES", TokenEnum.META_ATTRIBUTES),
  # keywords
  "import": ("IMPORT", TokenEnum.KEYWORDS),
  "relator": ("RELATOR", TokenEnum.KEYWORDS),
  "specializes": ("SPECIALIZES", TokenEnum.KEYWORDS),
  "of": ("OF", TokenEnum.KEYWORDS),
  "datatype": ("DATATYPE", TokenEnum.KEYWORDS),
  "enum": ("ENUM", TokenEnum.KEYWORDS),
  "relation": ("RELATION", TokenEnum.KEYWORDS),
  "genset": ("GENSET", TokenEnum.KEYWORDS),
  "disjoint": ("DISJOINT", TokenEnum.KEYWORDS),
  "complete": ("COMPLETE", TokenEnum.KEYWORDS),
  "general": ("GENERAL", TokenEnum.KEYWORDS),
  "specifics": ("SPECIFICS", TokenEnum.KEYWORDS),
  "where": ("WHERE", TokenEnum.KEYWORDS),
  "package": ("PACKAGE", TokenEnum.KEYWORDS),
  "relators": ("RELATORS", TokenEnum.KEYWORDS),
  "inverseOf": ("INVERSEOF", TokenEnum.KEYWORDS),
  "type": ("TYPE", TokenEnum.KEYWORDS),
  "collectives": ("COLLECTIVES", TokenEnum.KEYWORDS),
}

token_definitions = {
  TokenEnum.NEW_TYPE: r"[a-zA-Z]+DataType",
  TokenEnum.FUNCTIONAL_COMPLEXES: r"functional-complexes",
  TokenEnum.INTRINSIC_MODES: r"intrinsic-modes",
  TokenEnum.COMPOSITION_L: r"<>--",
  TokenEnum.COMPOSITION_R: r"--<>",
  TokenEnum.COMPOSITION_LO: r"<o>--",
  TokenEnum.COMPOSITION_RO: r"--<o>",
  TokenEnum.ASSOCIATION: r"--",
  TokenEnum.CARDINALITY: r"\[[\d\*\.]+\]",
  TokenEnum.INSTANCE_ID: r"[a-zA-Z_][a-zA-Z0-9_]*[0-9]",
  TokenEnum.CLASS_ID: r"[A-Z_][a-zA-Z_]*",
  TokenEnum.RELATION_ID: r"[a-z_][a-zA-Z_]*",
  # literals
  TokenEnum.LPAREN: r"\(",
  TokenEnum.RPAREN: r"\)",
  TokenEnum.LBRACE: r"\{",
  TokenEnum.RBRACE: r"\}",
  TokenEnum.DOT: r"\.",
  TokenEnum.COMMA: r",",
  TokenEnum.PLUS: r"\+",
  TokenEnum.LT: r"<",
  TokenEnum.GT: r">",
  TokenEnum.AT: r"@",
  TokenEnum.MINUS: r"-",
  TokenEnum.STAR: r"\*",
  TokenEnum.COLON: r":",
}
